AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  DataRetrievalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: DataRetrieval.handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_REGION: us-east-1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: hash_keys
        - DynamoDBCrudPolicy:
            TableName: scraped_data
      Events:
        ApiCatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "Your Swagger UI Docs Page"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/docs"
